Milestone 1 : Using Bootstrap (The Next Web)
ZeenatLawal/Project-3-Newsweek pull request #2
Opened 2021-04-05 14:43 UTC by ZeenatLawal

## The Next Web clone milestone 1: Responsive Design

In this milestone we:

- Added two sections to the site (Header and Footer)
- Used bootstrap's default media query breaking points
- Used bootstrap classes for the styling

2021-04-05 15:37 UTC, DeliceLydia requested changes
# Status: Change Requested

Amazing job so far @ZeenatLawal and @safafa you implemented almost all of the requirements for this project but you need to make some small changes to be ready for the next milestone
## To Highlights ![image](https://user-images.githubusercontent.com/44745855/113591323-087fef80-9634-11eb-96f9-6fc96fe9fa42.png)


- PR is professional
- Codes looks clean and easy to read
- README is descriptive

### Header

- The Newsweek logo has a link
- Logo In desktop it is centered
- In tablet and mobile, it is aligned to the left
- Contains a date in the same format on the source page (only on the desktop)
- Login and Subscribe have links
-  In mobile, the Login button changes into an icon
- 
### The main navigation (menu)
  * [x] Uses a nav tag
  * [ ] Each option has a link
  * [ ] It has a form with the search field
  * [ ] In mobile and table the menu hides, and show a hamburger button
* [ ] The size of the elements change in desktop, tablet, and mobile

## To Improve ![image](https://user-images.githubusercontent.com/44745855/113591231-ee461180-9633-11eb-979a-8f6803f4ea9c.png)

### Header
- The header has to fit the content on the mobile 

original

![original](https://user-images.githubusercontent.com/44745855/113592105-04a09d00-9635-11eb-8310-2d1f601326a2.png)

yours

![h1](https://user-images.githubusercontent.com/44745855/113592150-12562280-9635-11eb-8637-936e5ce6d85a.png)
Try to make it looks like the original

### Footer
- Newsweek logo is supposed to have a link
- The content-disposition changes to the correct place in desktop, tablet, and mobile

yours

![copy](https://user-images.githubusercontent.com/44745855/113590659-34e73c00-9633-11eb-8a44-b8f719c6ccf9.png)

Original

![og](https://user-images.githubusercontent.com/44745855/113590735-49c3cf80-9633-11eb-99fc-3ca53db619fc.png)

### Kindly fix that and submit another CRR and remember you still have only 2 code reviews and work accordingly

All the best,

Lydia Ingabire

2021-04-05 17:52 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @ZeenatLawal & @safafa  :wave:

__You've really done well so far. Here're the major highlights of this PR:__

- Almost all the required changes have been fixed :+1: 
- Codebase looks clean with a good naming structure :1st_place_medal: 
- Limited use of custom CSS rules :ok_hand: 

__However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

_**Note that you are asked to be more precise and to make sure that your page looks exactly the same as the source page**_

- [ ] The red background color at the top navbar is not the same as what we have on the original page. Since the color is not the same as the `danger` color of bootstrap, it is okay to use a custom CSS rule to specify the correct color. 
- [ ] Check my inline comment below and fix it as appropriate.

**[ OPTIONAL CHANGES ]**

- [ ] You've used the `id` attribute extensively as your CSS selectors. This will work, but it is not a very good CSS practice. You might want to change the `id` selectors to `class` selectors.

* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

**REMINDER: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 1 code review left for this project. If you think that the code review was not fair, you can [request a second-opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).**

_**Please make the required changes and submit another review request when you are done.**_

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-04-05 17:52 UTC, teekaytech commented on index.html
> +            <a class="nav-link disabled" href="#">Search <i class="fas fa-search"></i></a>
This should be a form with the search field and not just the search icon.

2021-04-06 09:41 UTC, Elbie-em approved these changes
## STATUS: APPROVED :heavy_check_mark:

Hello @safafa and @ZeenatLawal, good job implementing changes requested by the previous TSE and I will therefore approve this milestone.

## [OPTIONAL]

- Please ensure you apply the changes below requested in your first review accordingly before moving on.
     - [ ]  Your nav in the mobile version should look like the original. Apply changes to your news week logo, subscribe button, and spacing between elements in your navbar.

**Orginal** 
         
![Screenshot 2021-04-06 at 11 01 59](https://user-images.githubusercontent.com/57832450/113690479-bc808980-96cb-11eb-82af-13f45a588719.png)
      **Yours**
![Screenshot 2021-04-06 at 11 25 05](https://user-images.githubusercontent.com/57832450/113690530-cefac300-96cb-11eb-85f1-410ac2b0073a.png)

 - [ ]  Please make sure your content-disposition changes to the correct place on desktop, tablet, and mobile. This fix has not been applied and I recommend you do it.
 
**Orginal**
![Screenshot 2021-04-06 at 11 00 45](https://user-images.githubusercontent.com/57832450/113691312-95768780-96cc-11eb-9d30-28bef79bd94d.png)

**Yours**
![Screenshot 2021-04-06 at 11 25 17](https://user-images.githubusercontent.com/57832450/113691350-9dcec280-96cc-11eb-8fb0-929e888c7c5c.png)

*If you have any questions, you can reach me on slack using Elbie Moonga*

2021-04-06 09:50 UTC, merged