Sections milestone
ZeenatLawal/Project-3-Newsweek pull request #3
Opened 2021-04-06 10:06 UTC by ZeenatLawal

2021-04-06 21:24 UTC, Dipeshtwis requested changes
# Status:  ♻️ Changes Required ♻️
 Hi @ZeenatLawal  and @safafa

**You've really hit all the requirements in one shot. Well done.** Here're the major highlights of this PR:
- Your PR title and description are really descriptive.
- The content order and disposition changes to the correct place on the desktop, tablet, and mobile.

**However, in order to approve, we have to work a little bit more. Please check my comments below and fix them as appropriate.**

## For Approval

- [ ] All images should have links.
- [ ] All the titles should have a link and more font-weight.

- [ ] The free sign-up text should be aligned. I have made the border.

![Screenshot (1303)_LI](https://user-images.githubusercontent.com/22434660/113778933-9fd76680-974a-11eb-8e08-6d710dcbf6f5.jpg)

- [ ] This sponsored insight is breaking in 992px to 1087px. What I will suggest you to reduce the font size.

![Screenshot (1304)_LI](https://user-images.githubusercontent.com/22434660/113779405-47ed2f80-974b-11eb-853f-071bb8536f08.jpg)

## [Optional]

- [x] I will recommend giving a little bit more gap from the side. It's okay as well if you don't give.

![Screenshot (1305)_LI](https://user-images.githubusercontent.com/22434660/113779796-dd88bf00-974b-11eb-991a-589729367c35.jpg)

Remember, This is optional and nothing to do with the project approval.

## Please make the required changes and submit another review request when you are done.

## Reminder

**"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) now, you have only 2 code review left for this project."**

(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions).
Happy Coding
[Dipesh Kumar](https://deeptwist.tk)
[Twitter](https://twitter.com/97deepeshkumar)

2021-04-06 21:24 UTC, Dipeshtwis commented on index.html
> +                    <article class="border-bottom border-2 mb-3 pb-2">
All the titles should have some more font-weight so that it looks the same.

2021-04-07 09:33 UTC, Berabjesus requested changes
## Status: CHANGES REQUIRED :warning: :construction:

Hi  @ZeenatLawal  and @safafa  You have done really awesome applying the requested changes :+1: ! Awesome README :100: Good job with the professional PR :tada: 

### However, you do have one change to make that was requested in the previous review.

- [ ] All the titles should have a link and more font-weight. (Each title uses a hx tag and have a link) - Check the comment below.

**❗ You have one(1) remaining review left. As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), when you reach to the limit of 3 code reviews and your project was not approved, you will need to repeat the project. If you think that the code review was not fair, you can [request a second-opinion using this form.](https://airtable.com/shrmBIv6cXYrq4Fgv)**

#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-04-07 09:33 UTC, Berabjesus commented on style.css
> +}
- [ ] [OPTIONAL] avoid using rules that you can already apply using bootstrap.
- In this case `position: absolute;`, ` text-align: center;`, `font-weight: bold;` can be used with bootstrap

2021-04-07 09:33 UTC, Berabjesus commented on index.html
> +                            <h5 class="text-secondary my-4 my-md-2">'I Married My Best Friend to Avoid Inheritance Tax' </h5>
- [ ] All the titles should have a link and more font-weight. (Each title uses a hx tag and has a link) - Check the comment below. As you can see on the original website, this and all the other similar headers are links. So please add the appropriate anchor tag.

2021-04-07 11:06 UTC, descholar-ceo approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @ZeenatLawal and @safafa  , your project is approved :tada: :tada: :tada: 

You have implemented all rquested changes from the previous review, so I am marking this project as complete, but before merging all changes to the base branch, I would highly recommend you remove the white space which is on the top of the navbar, looking at the original website, the navbar is touching the top border of the viewport,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2021-04-07 12:32 UTC, merged